INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_OSMOCORE "libosmocore")

message("CHECKING FOR OSMOCORE")
if(PC_OSMOCORE_FOUND)
    FIND_PATH(OSMOCORE_INCLUDE_DIRS
        NAMES osmocom/core/application.h
        HINTS ${PC_OSMOCORE_INCLUDE_DIR}
        PATHS
        /usr/local/include
        /usr/include
    )
    message(" * INCLUDES=" ${OSMOCORE_INCLUDES})

    FIND_LIBRARY(OSMOCORE_LIBRARIES
        NAMES osmocore
        HINTS ${PC_OSMOCORE_LIBDIR}
        PATHS
        ${OSMOCORE_INCLUDE_DIRS}/../lib
        /usr/local/lib
        /usr/lib
    )
    LIST(APPEND OSMOCORE_LIBRARIES ${CMAKE_DL_LIBS})
    message(" * LIBRARIES=" ${OSMOCORE_LIBRARIES})

    set(OSMOCORE_FOUND ${PC_GNURADIO_RUNTIME_FOUND})
endif(PC_OSMOCORE_FOUND)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSMOCORE DEFAULT_MSG OSMOCORE_LIBRARIES OSMOCORE_INCLUDE_DIRS)
MARK_AS_ADVANCED(OSMOCORE_LIBRARIES OSMOCORE_INCLUDE_DIRS)
